### ISSUE TITLE
The script gets stuck

### ISSUE THREAD

**Issue by blobikcnn** [mambles/SmartAutoMD#23]
To recreate,just keep it running for a while,the part i have been stuck on is the ego gift "cancel" button

**Comment by blobikcnn** [comment]
some other parts are also bugged,there are like 2 or 3 of them,i can't really pinpoint them if im not running the script for a hour

**Comment by blobikcnn** [comment]
<img width="1914" height="1003" alt="Image" src="https://github.com/user-attachments/assets/589a01aa-dbd0-44bb-8317-42b251fbc775" />
This is the part where it gets stuck. It tries to pick cancel,stucking in a loop

**Comment by MANGNAN1** [comment]
Currently, it seems the program freezes because only RandomGift and Resource are present. Adding the Starlight image and inserting

```"Starlight3.png": (7, 3, None, None, None),```
between lines 212 and 213, and also adding

```
"Starlight3.png": [
    ("move_click", None, True, 0.25),
    ("move_click", (1185, 788), True, 0),
],
```
between lines 652 and 653, makes the program work correctly in this situation as well.

**Comment by blobikcnn** [comment]
After the "claim rewards",the script just freezes and doesn't do anything.  To be exact,the script doesn't press "confirm"

**Comment by mambles** [comment]
should be fixed with newest update

**Comment by xNotDaniel** [comment]
Hello, sadly it isn't fixed yet because I encounter this exact same bug (running Rupture too) today
